import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { PriorityBadge } from "@/components/ui/badge";
import { Sparkline } from "@/components/charts/sparkline";
import type { Issue } from "@/lib/types";
import { signed } from "@/lib/utils/format";

export function IssueTable({ issues }: { issues: Issue[] }) {
  return <div className="overflow-x-auto"><table className="w-full min-w-[850px] border-collapse text-left"><thead className="border-b border-line bg-surface-sunken text-xs font-bold tracking-wide text-muted"><tr><th className="px-4 py-3">Issue / category</th><th className="px-3 py-3">Priority</th><th className="px-3 py-3">Feedback</th><th className="px-3 py-3">Behavior signal</th><th className="px-3 py-3">Confidence</th><th className="px-3 py-3">Build</th><th className="px-4 py-3"><span className="sr-only">Open</span></th></tr></thead><tbody>{issues.map((issue) => <tr key={issue.id} className="border-b border-line transition-colors last:border-0 hover:bg-surface-raised"><td className="px-4 py-3"><Link href={`/issues/${issue.id}`} className="font-semibold text-ink hover:text-accent-strong">{issue.title}</Link><p className="mt-1 text-xs text-muted">{issue.category.replaceAll("_", " ")}</p></td><td className="px-3 py-3"><PriorityBadge priority={issue.priority} /></td><td className="px-3 py-3 font-mono text-sm text-ink">{issue.feedbackMentions.toLocaleString()} <span className={issue.feedbackGrowth > 0 ? "text-critical" : "text-low"}>{signed(issue.feedbackGrowth)}</span></td><td className="px-3 py-3"><div className="flex items-center gap-2"><Sparkline values={issue.sparkline} tone={issue.priority === "LOW" ? "low" : "critical"} label={`Quit rate trend ${signed(issue.quitRateChange)}`} /><span className="font-mono text-xs text-critical">quit {signed(issue.quitRateChange)}</span></div></td><td className="px-3 py-3 font-mono text-sm text-accent-strong">{issue.correlationConfidence}% <span className="text-xs text-low">+6 pts</span></td><td className="px-3 py-3 font-mono text-sm text-muted">{issue.affectedBuild}</td><td className="px-4 py-3"><Link href={`/issues/${issue.id}`} aria-label={`Inspect ${issue.title}`} className="text-muted hover:text-accent-strong"><ArrowUpRight size={17} /></Link></td></tr>)}</tbody></table></div>;
}
